apiVersion: apps/v1
kind: Deployment
metadata:
  name: revhire-eks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revhire-app
  template:
    metadata:
      labels:
        app: revhire-app
    spec:
      containers:
      - name: revhire-app
        image: modassir7488/revhire_frontend:latest 
        ports:
        - containerPort: 4200